-- AlterTable
ALTER TABLE "User" ADD COLUMN     "avgAnswerTime" DOUBLE PRECISION NOT NULL DEFAULT 0.0,
ADD COLUMN     "losses" INTEGER NOT NULL DEFAULT 0,
ADD COLUMN     "wins" INTEGER NOT NULL DEFAULT 0,
ALTER COLUMN "mbrr" SET DEFAULT 1000;
